/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* CATEGORY */
export const CATEGORY_GET_LIST = 'CATEGORY_GET_LIST';
export const CATEGORY_GET_LIST_SUCCESS = 'CATEGORY_GET_LIST_SUCCESS';
export const CATEGORY_GET_LIST_ERROR = 'CATEGORY_GET_LIST_ERROR';
export const CATEGORY_SELECTED_ITEMS_CHANGE = 'CATEGORY_SELECTED_ITEMS_CHANGE';
export const CATEGORY_GET_LIST_WITH_FILTER = 'CATEGORY_GET_LIST_WITH_FILTER';
export const CATEGORY_GET_LIST_WITH_ORDER = 'CATEGORY_GET_LIST_WITH_ORDER';
export const CATEGORY_GET_LIST_SEARCH = 'CATEGORY_GET_LIST_SEARCH';

export * from './menu/actions';
export * from './auth/actions';
export * from './category/actions';
